# Numpy
Introduction to Numpy. Array, Creation,Printing Arrays, Basic Operations- Indexing, Slicing and Iterating
Shape Manipulation - Changing shape,stacking and spliting of array Vector stacking, 
Filtering values from an Array

In [0]:
import numpy as np

In [0]:
len(dir(np))

612

In [0]:
tmp = np.array([])
tmp

array([], dtype=float64)

In [0]:
tmp = np.array([1,2,3])
tmp

array([1, 2, 3])

In [0]:
tmp = np.array([[1,2,3],[4,5,6],[4,2,7]])
tmp

array([[1, 2, 3],
       [4, 5, 6],
       [4, 2, 7]])

In [0]:
tmp = np.array([[1,2,3],[4,5,6],[4,2,7]],dtype="int8")
tmp

array([[1, 2, 3],
       [4, 5, 6],
       [4, 2, 7]], dtype=int8)

In [0]:
print(tmp.dtype)
print(tmp.shape)
print(tmp.ndim)
print(tmp.size)
print(tmp.itemsize)

int8
(3, 3)
2
9
1


# reshaping array

In [0]:
tmp = np.arange(10)
tmp.shape

(10,)

In [0]:
tmp = np.arange(10).reshape(5,2)
print(tmp)
tmp.shape

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


(5, 2)

In [0]:
tmp = np.arange(10).reshape(2,5)
print(tmp)
tmp.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [0]:
tmp = np.arange(10).reshape(1,10)
print(tmp)
tmp.shape

[[0 1 2 3 4 5 6 7 8 9]]


(1, 10)

In [0]:
m1 = np.array([[1,2,3],[1,1,1],[2,2,2]])
m2 = np.array([[3,3,3],[1,1,1],[0,0,0]])
print(m1,"\n\n",m2)

[[1 2 3]
 [1 1 1]
 [2 2 2]] 

 [[3 3 3]
 [1 1 1]
 [0 0 0]]


In [0]:
print(m1+m2)
print(m1**m2)
print(m1*m2)
print(m1/m2)

[[4 5 6]
 [2 2 2]
 [2 2 2]]
[[ 1  8 27]
 [ 1  1  1]
 [ 1  1  1]]
[[3 6 9]
 [1 1 1]
 [0 0 0]]
[[ 0.33333333  0.66666667  1.        ]
 [ 1.          1.          1.        ]
 [        inf         inf         inf]]


C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [0]:
print(np.dot(m1,m2)) # To be used for matrix multiplication

[[5 5 5]
 [4 4 4]
 [8 8 8]]


# Random numbers

In [0]:
t1 = np.random.randint(1,50,20).reshape(5,4)
print(t1)

[[37  2  2 29]
 [16 31 47 14]
 [36 43  6 43]
 [42 15  7 48]
 [23  6 43  2]]


In [0]:
t1[2][2]
# or 

45

In [0]:
t1[2,2] # [row:col:<step>]

45

In [0]:
print(t1)

[[19 26 33 20]
 [32 23 15  2]
 [19 14 45 27]
 [42 43 36 29]
 [47 17 45 31]]


# Slicing

In [0]:
# print(t1[::])
# print(t1[::,::])
# print(t1[::-1,::])
# print(t1[::-1,::-1])
# print(t1[2:-1:,])
# print(t1[:3,1:3])
# print(t1[,1:3])

# Stacking

In [0]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[0,1,5],[9,3,7]])

In [0]:
print(m1)
print("\n")
print(m2)

[[1 2 3]
 [4 5 6]]


[[0 1 5]
 [9 3 7]]


In [0]:
np.vstack([m1,m2])

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 5],
       [9, 3, 7]])

In [0]:
np.hstack([m1,m2])

array([[1, 2, 3, 0, 1, 5],
       [4, 5, 6, 9, 3, 7]])

# Statistics functions

In [0]:
tmp2 = np.random.randint(1,10,25).reshape(5,5)
print(tmp2)

[[5 7 4 5 9]
 [5 5 7 3 5]
 [8 2 3 1 3]
 [3 1 5 2 3]
 [9 8 6 8 8]]


In [0]:
print(tmp2.sum())
print(tmp2.std())
print(tmp2.mean())

125
2.43310501212
5.0


In [0]:
print(tmp2.std(axis=0)) # axis=0 col and axis= 1 row
print(tmp2.std(axis=1))

[ 2.19089023  2.72763634  1.41421356  2.48193473  2.4979992 ]
[ 1.78885438  1.26491106  2.41660919  1.32664992  0.9797959 ]


In [0]:
print(tmp2[3].std())

1.32664991614


# Filtering values from an Array

In [0]:
# Syntax:
#     np.where(<condition>)
#     np.where((<condition1>) & (<condition2..>))
#     will return indices of row and col

In [0]:
tmp3 = np.random.randint(1,90,100).reshape(10,10)
tmp3

array([[34, 16, 17, 64, 26, 53, 31, 35,  4, 55],
       [50, 33,  4, 32, 40, 71, 35, 58, 42, 80],
       [71, 26, 80, 38, 30, 72,  2, 32, 76, 49],
       [67, 44, 22, 73, 18, 52, 55, 75, 59, 43],
       [49, 51, 63, 65, 37, 33, 48, 49, 51, 62],
       [40, 71, 55, 86, 14,  2, 82, 58, 85, 16],
       [57, 12, 49, 46, 65,  4, 46, 55, 72, 70],
       [74, 27, 77, 51, 68, 31, 68, 19, 31, 89],
       [81, 10, 50, 78,  7, 46, 68, 24, 22, 13],
       [10, 80, 33, 19, 55, 43, 56, 19, 61, 42]])

In [0]:
np.where(tmp3>30)

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3,
        3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5,
        5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9,
        9, 9, 9, 9, 9, 9], dtype=int64),
 array([0, 3, 5, 6, 7, 9, 0, 1, 3, 4, 5, 6, 7, 8, 9, 0, 2, 3, 5, 7, 8, 9, 0,
        1, 3, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 6, 7,
        8, 0, 2, 3, 4, 6, 7, 8, 9, 0, 2, 3, 4, 5, 6, 8, 9, 0, 2, 3, 5, 6, 1,
        2, 4, 5, 6, 8, 9], dtype=int64))

In [0]:
tmp3[np.where(tmp3>30)]

array([34, 64, 53, 31, 35, 55, 50, 33, 32, 40, 71, 35, 58, 42, 80, 71, 80,
       38, 72, 32, 76, 49, 67, 44, 73, 52, 55, 75, 59, 43, 49, 51, 63, 65,
       37, 33, 48, 49, 51, 62, 40, 71, 55, 86, 82, 58, 85, 57, 49, 46, 65,
       46, 55, 72, 70, 74, 77, 51, 68, 31, 68, 31, 89, 81, 50, 78, 46, 68,
       80, 33, 55, 43, 56, 61, 42])

In [0]:
tmp3[np.where(tmp3>30)].size

75

# zeros

In [0]:
np.zeros([3,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

# Ones

In [0]:
np.ones([3,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

# Create a square mtarix of 10,10 and make all the upper diagonal values to zero and same thing with lower triangle

In [0]:
tmp4 = np.random.randint(1,500,100).reshape(10,10)
tmp4

array([[278, 150, 215, 247, 382, 202, 471, 123, 450, 272],
       [499, 284, 294, 258, 458, 211,   2, 412, 177, 177],
       [371,  84, 441,   7, 385, 174,  14,  25, 470, 263],
       [ 99, 129,   4, 374, 136, 436, 317,  15, 490, 322],
       [105, 236, 135, 260, 350, 457,  26, 175, 150, 217],
       [473, 458, 161,  38, 374, 155, 402, 157, 432, 136],
       [327, 298, 155, 430, 361, 205,   1, 494, 400, 147],
       [ 59, 288, 275, 326, 435, 235,  92, 442,  93,  30],
       [293, 478, 148, 362, 328, 131, 118, 381,  31,   1],
       [203, 403,  60, 318, 342, 314, 485, 327, 236, 193]])

# For Upper triangle

In [0]:
cnt = 0
for i in range(len(tmp4)):
    tmp = tmp4[i]
    tmp[cnt+1:] = 0
    cnt += 1
tmp4

array([[193,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [248, 260,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 82, 176, 229,   0,   0,   0,   0,   0,   0,   0],
       [208, 174,   4, 452,   0,   0,   0,   0,   0,   0],
       [ 51,  66, 488, 149, 479,   0,   0,   0,   0,   0],
       [ 64, 487, 125, 115, 260,  28,   0,   0,   0,   0],
       [396, 499, 353,  59,  85, 258,  30,   0,   0,   0],
       [432, 268, 430, 262, 164, 121, 455, 329,   0,   0],
       [273, 117, 319,  28, 289, 262,  30, 469, 376,   0],
       [475, 497, 250, 145, 473, 132, 161,  74, 221,  58]])

# For Lower triangle

In [0]:
tmp5 = np.random.randint(1,500,100).reshape(10,10)
cnt = 0
for i in range(len(tmp5)):
    tmp = tmp5[i]
    tmp[:cnt] = 0
    cnt += 1
tmp5

array([[320,  34, 271, 133, 323, 290, 435, 449, 207,  43],
       [  0, 278, 379, 387, 444, 409,  78,  36, 164, 279],
       [  0,   0, 363, 309, 200,  54,  62, 356, 440,   7],
       [  0,   0,   0, 396, 147, 285, 140, 149, 383, 359],
       [  0,   0,   0,   0,  48,  27, 480, 371, 357, 495],
       [  0,   0,   0,   0,   0, 438, 382, 124,  69,  42],
       [  0,   0,   0,   0,   0,   0, 206, 159, 253, 140],
       [  0,   0,   0,   0,   0,   0,   0, 130, 457, 142],
       [  0,   0,   0,   0,   0,   0,   0,   0, 350,  98],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  62]])

In [0]:
tmp5 = np.random.randint(1,500,100).reshape(10,10)
cnt = 0
for row in (tmp5):
    row[:cnt] = 0
    cnt += 1
tmp5

array([[ 29,  53,  50, 172, 176, 388, 384,  60, 216, 319],
       [  0, 304, 141, 382,  22, 382, 441, 448,  37, 367],
       [  0,   0, 365,  37, 273, 487, 179, 487, 167,  88],
       [  0,   0,   0, 278, 111,  22, 217,  55, 496, 284],
       [  0,   0,   0,   0,  57, 222, 220, 486, 324, 249],
       [  0,   0,   0,   0,   0, 449,  13, 457, 486,  27],
       [  0,   0,   0,   0,   0,   0,  24, 163, 205, 239],
       [  0,   0,   0,   0,   0,   0,   0, 323, 465,  35],
       [  0,   0,   0,   0,   0,   0,   0,   0,  22, 428],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 254]])